export const enableCaret = 'true'
export const enableRounded = 'true'
export const enableShadows = 'false'
export const enableGradients = 'false'
export const enableTransitions = 'true'
export const enableHoverMediaQuery = 'false'
export const enableGridClasses = 'true'
export const enablePrintStyles = 'true'
